#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-stargazer
Version  : 5.2.2
Release  : 1
URL      : https://cran.r-project.org/src/contrib/stargazer_5.2.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/stargazer_5.2.2.tar.gz
Summary  : Well-Formatted Regression and Summary Statistics Tables
Group    : Development/Tools
License  : GPL-2.0+
BuildRequires : buildreq-R

%description
regression analysis results from several models side-by-side, as well as summary
    statistics.

%prep
%setup -q -c -n stargazer

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1573405158

%install
export SOURCE_DATE_EPOCH=1573405158
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library stargazer
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library stargazer
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library stargazer
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc stargazer || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/stargazer/CITATION
/usr/lib64/R/library/stargazer/ChangeLog
/usr/lib64/R/library/stargazer/DESCRIPTION
/usr/lib64/R/library/stargazer/INDEX
/usr/lib64/R/library/stargazer/Meta/Rd.rds
/usr/lib64/R/library/stargazer/Meta/features.rds
/usr/lib64/R/library/stargazer/Meta/hsearch.rds
/usr/lib64/R/library/stargazer/Meta/links.rds
/usr/lib64/R/library/stargazer/Meta/nsInfo.rds
/usr/lib64/R/library/stargazer/Meta/package.rds
/usr/lib64/R/library/stargazer/Meta/vignette.rds
/usr/lib64/R/library/stargazer/NAMESPACE
/usr/lib64/R/library/stargazer/R/stargazer
/usr/lib64/R/library/stargazer/R/stargazer.rdb
/usr/lib64/R/library/stargazer/R/stargazer.rdx
/usr/lib64/R/library/stargazer/doc/index.html
/usr/lib64/R/library/stargazer/doc/stargazer.Rtex
/usr/lib64/R/library/stargazer/doc/stargazer.pdf
/usr/lib64/R/library/stargazer/help/AnIndex
/usr/lib64/R/library/stargazer/help/aliases.rds
/usr/lib64/R/library/stargazer/help/paths.rds
/usr/lib64/R/library/stargazer/help/stargazer.rdb
/usr/lib64/R/library/stargazer/help/stargazer.rdx
/usr/lib64/R/library/stargazer/html/00Index.html
/usr/lib64/R/library/stargazer/html/R.css
